import { StyleSheet } from 'react-native';

import Colors from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F8F7',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 58,
    paddingBottom: 12,
    gap: 12,
  },
  greeting: { fontSize: 14, color: Colors.gray600 },
  title: { fontSize: 26, fontWeight: '700', color: '#132018', marginTop: 4 },
  alertButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DDE6E1',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.white,
  },
  alertButtonText: { color: '#22352B', fontSize: 12, fontWeight: '700' },
  alertBanner: {
    marginHorizontal: 24,
    marginBottom: 12,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 184, 0, 0.35)',
  },
  alertGradient: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  alertText: { color: '#A96400', fontWeight: '600' },
  feedToggle: {
    flexDirection: 'row',
    marginHorizontal: 24,
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: Colors.white,
    padding: 4,
    gap: 4,
    borderWidth: 1,
    borderColor: '#DDE6E1',
  },
  feedButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  feedButtonActive: {
    backgroundColor: Colors.primary,
  },
  feedButtonText: {
    color: Colors.gray600,
    fontSize: 13,
    fontWeight: '700',
  },
  feedButtonTextActive: {
    color: Colors.white,
  },
  cardContainer: { flex: 1 },
  skeletonWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  skeletonCard: {
    width: '82%',
    aspectRatio: 0.78,
    borderRadius: 22,
    backgroundColor: '#E8EFEC',
    borderWidth: 1,
    borderColor: '#DDE6E1',
    position: 'absolute',
  },
  skeletonCardBack: {
    transform: [{ scale: 0.95 }, { translateY: -8 }],
    opacity: 0.6,
  },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 24 },
  emptyTitle: { color: '#132018', fontSize: 20, fontWeight: '700', marginBottom: 8 },
  emptyText: { color: Colors.gray600, textAlign: 'center' },
  retryButton: {
    marginTop: 12,
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryButtonText: { color: Colors.white, fontWeight: '700' },
  footerActions: {
    paddingBottom: 90,
    alignItems: 'center',
  },
  footerButton: {
    borderRadius: 12,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#DDE6E1',
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  footerButtonText: { color: '#22352B', fontWeight: '700' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 33, 24, 0.34)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: '#DDE6E1',
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalTitle: { color: '#132018', fontSize: 20, fontWeight: '700', flex: 1 },
  favoriteButton: {
    backgroundColor: 'rgba(255, 184, 0, 0.16)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  favoriteButtonText: {
    color: '#A96400',
    fontWeight: '700',
    fontSize: 12,
  },
  modalDesc: { color: Colors.gray700, marginBottom: 12, marginTop: 6 },
  sectionTitle: { color: Colors.primaryDark, fontWeight: '700', marginTop: 8, marginBottom: 4 },
  listText: { color: '#22352B', fontSize: 13, marginBottom: 3 },
  missingIngredientText: { color: Colors.danger },
  addMissingButton: {
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 71, 87, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 71, 87, 0.2)',
    paddingVertical: 10,
    alignItems: 'center',
  },
  addMissingButtonText: { color: Colors.danger, fontWeight: '700' },
  servingsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginTop: 12 },
  servingsButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E8EFEC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  servingsButtonText: { color: '#22352B', fontSize: 18, fontWeight: '700' },
  servingsText: { color: '#22352B', fontWeight: '600' },
  modalActions: { flexDirection: 'row', marginTop: 14, gap: 10 },
  cancelButton: {
    flex: 1,
    backgroundColor: '#E8EFEC',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  cancelButtonText: { color: '#22352B', fontWeight: '700' },
  cookButton: { flex: 1, backgroundColor: Colors.primary, borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  cookButtonText: { color: Colors.white, fontWeight: '700' },
});
