import { StyleSheet } from 'react-native';

import Colors from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F8F7',
  },
  permissionContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    backgroundColor: '#F5F8F7',
  },
  permissionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#132018',
    marginBottom: 10,
    textAlign: 'center',
  },
  permissionText: {
    fontSize: 15,
    color: Colors.gray600,
    marginBottom: 24,
    textAlign: 'center',
  },
  camera: {
    flex: 1,
  },
  cameraHeader: {
    paddingTop: 60,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  cameraTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: Colors.white,
    marginBottom: 8,
  },
  cameraSubtitle: {
    fontSize: 14,
    color: Colors.gray300,
    textAlign: 'center',
  },
  scanTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    marginTop: 20,
  },
  scanTypeButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
  },
  scanTypeButtonActive: {
    backgroundColor: Colors.primary,
  },
  scanTypeText: {
    color: Colors.gray300,
    fontSize: 13,
    fontWeight: '700',
  },
  scanTypeTextActive: {
    color: Colors.white,
  },
  scanFrame: {
    flex: 1,
    margin: 40,
    position: 'relative',
  },
  corner: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderColor: Colors.primary,
  },
  cornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 12,
  },
  cornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 12,
  },
  cornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 12,
  },
  cornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 12,
  },
  cameraControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 100,
    paddingHorizontal: 36,
  },
  galleryButton: {
    width: 64,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  captureButton: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: Colors.white,
  },
  captureButtonInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.white,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 24,
    paddingBottom: 16,
  },
  backButton: {
    fontSize: 16,
    color: Colors.primaryDark,
    fontWeight: '700',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#132018',
  },
  previewContainer: {
    height: 280,
    marginHorizontal: 24,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#E8EFEC',
    borderWidth: 1,
    borderColor: '#DDE6E1',
  },
  previewImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  analyzingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(17, 33, 24, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  analyzingText: {
    color: Colors.white,
    fontSize: 15,
    marginTop: 12,
  },
  errorBanner: {
    marginHorizontal: 24,
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 71, 87, 0.3)',
    backgroundColor: 'rgba(255, 71, 87, 0.08)',
    padding: 12,
  },
  errorText: {
    color: Colors.danger,
    fontSize: 13,
  },
  errorRetryButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 71, 87, 0.16)',
  },
  errorRetryText: {
    color: Colors.danger,
    fontWeight: '700',
    fontSize: 12,
  },
  resultContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 18,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#132018',
    marginBottom: 12,
  },
  resultScroll: {
    flex: 1,
  },
  resultScrollContent: {
    paddingBottom: 8,
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#DDE6E1',
  },
  resultItemInfo: {
    flex: 1,
  },
  resultItemName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#132018',
  },
  resultItemQty: {
    fontSize: 13,
    color: Colors.gray600,
    marginTop: 2,
  },
  categorySelectorRow: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 6,
  },
  categoryChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#DDE6E1',
    backgroundColor: '#F9FBFA',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  categoryChipActive: {
    borderColor: Colors.primary,
    backgroundColor: '#E8F8F2',
  },
  categoryChipText: {
    color: Colors.gray700,
    fontSize: 11,
    fontWeight: '700',
  },
  categoryChipTextActive: {
    color: Colors.primaryDark,
  },
  confidenceBadge: {
    backgroundColor: '#E8F8F2',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  confidenceText: {
    color: Colors.primaryDark,
    fontSize: 12,
    fontWeight: '700',
  },
  rawTextBox: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DDE6E1',
    backgroundColor: Colors.white,
    padding: 12,
  },
  rawTextTitle: {
    color: Colors.primaryDark,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  rawText: {
    color: Colors.gray700,
    fontSize: 12,
    lineHeight: 18,
  },
  actionContainer: {
    paddingHorizontal: 24,
    paddingBottom: 96,
    paddingTop: 16,
    alignItems: 'center',
  },
  roundButtonIcon: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  actionSpacer: {
    height: 10,
  },
});
